### ISSUE TITLE
As a player, I want information on the monsters I'm fighting in combat so I can get a better understanding of my situation in combat.

### ISSUE THREAD

**Issue by x183** [Krysset/TDA367-Projektgrupp-16#32]
- [ ] Design enemy hp interface
- [ ] Implement enemy hp interface

**Comment by Supergamer1337** [comment]
![image](https://user-images.githubusercontent.com/46903500/189346768-960a5ab8-7b08-4b7c-ad82-87ad9bb38f51.png)
