### ISSUE TITLE
As a player I want to be able send orders in combat

### ISSUE THREAD

**Issue by x183** [Krysset/TDA367-Projektgrupp-16#9]
create a draft for the combat UI, should include options to attack, change monster, use items and escape battle

**Comment by Supergamer1337** [comment]
![image](https://user-images.githubusercontent.com/46903500/189346768-960a5ab8-7b08-4b7c-ad82-87ad9bb38f51.png)

**Comment by Supergamer1337** [comment]
![image](https://user-images.githubusercontent.com/46903500/189346768-960a5ab8-7b08-4b7c-ad82-87ad9bb38f51.png)
